### ISSUE TITLE
Delete notification

### ISSUE THREAD

**Issue by MerrionComputing** [MerrionComputing/EventsSourcing-on-Azure-Functions#36]
When an event stream is **deleted** this also needs to raise a notification via eventhub,

**Comment by bartelink** [comment]
🤔 Do you also do soft deletes / tombstoning ? (For instance, in CosmosDB, and many other stores, you don't get notification of deletes; thus I'd question hooking deletes and instead be looking for a feature where one can do some form of tombstoning for a stream that needs to be forgotten or similar)

**Comment by MerrionComputing** [comment]
I don't really - but I am thinking this through.

My thought are that a _deleted for business reasons_ thing should be an **event** on the event stream that can be seen by a **classifier** that marks the entity as deleted.

True deletion of event streams is something that should happen to event stream backed entities with an intentionally short lifespan like commands, queries, sagas and so on.

**Comment by MerrionComputing** [comment]
Added - 
`EVENT_TYPE = @"eventsourcing.DeletedEntity"`

**Comment by MerrionComputing** [comment]
Tested notification - can close this now.
