### ISSUE TITLE
Missing dependency: Microsoft.Extensions.Configuration 5.0.0.0

### ISSUE THREAD

**Issue by MerrionComputing** [MerrionComputing/EventsSourcing-on-Azure-Functions#49]
`EventSourcingOnAzureFunctions.Common: Could not load file or assembly 'Microsoft.Extensions.Configuration, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
`
Occurred after update to visual studio

**Comment by MerrionComputing** [comment]
In debug it throws on loading:
Microsoft.Extensions.Configuration.Abstractions, Version=5.0.0.0

at 
`
builder.AddAppSettingsToConfiguration();`

**Comment by MerrionComputing** [comment]
Aha - https://github.com/Azure/azure-functions-core-tools/issues/2304#issuecomment-735454326

**Comment by MerrionComputing** [comment]
Rolled back Microsoft,Extension.* to 3.1.1.0

**Comment by therealkungfury** [comment]
I ran into this issue as well with Microsoft.Extensions.Logging.Abstractions.dll v7.0.0 after adding Microsoft.EntityFrameworkCore.SqlServer v7.0.1 to my function project. Long story short this blog post saved most of my hair https://bryanknox.github.io/2022/07/15/functionsskipcleanoutput-and-functionspreserveddependencies.html

Adding this to my .csproj fixed the issue
`
<ItemGroup>
   <FunctionsPreservedDependencies Include="Microsoft.Extensions.Logging.Abstractions.dll" />
</ItemGroup>
`
